# Đăng ký người dùng
POST http://localhost:3000/user/register
Content-Type: application/json

{
  "userName": "HienHo",
  "email": "1@example.com",
  "password": "1",
  "img": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
}

###

# Đăng nhập
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "1",
  "password": "1"
}

###

# Cập nhật thông tin cá nhân
PATCH http://localhost:3000/user/update/659d70dfd9b0257cdeeb66e5
Content-Type: application/json

{
  "userName": "HienHo",
  "img": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
}

###

## Tạo gia đình mới
POST http://localhost:3000/family/create
Content-Type: application/json

{
  "name": "Gia đình A",
  "image": "",
  "createBy": {
    "id": "659d70dfd9b0257cdeeb66e5",
    "userName": "HienHo",
    "email": "1",
    "image": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
  },
  "newMembers": [{
    "id": "659d77d32da0e7be026ce7df",
    "userName": "HienHo2",
    "email": "12",
    "image": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
  }]
}


###

# Lấy thông tin gia đình
GET http://localhost:3000/family/659e20a45da16547233431dc

###

# Xoá gia đình
DELETE http://localhost:3000/family/delete/659e20a45da16547233431dc


###
# Cập nhật ảnh gia đình
PATCH http://localhost:3000/family/updateImage/659d783a77408cb12f888ae8
Content-Type: application/json

{
     "image": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
}






###
# Tạo task mới
POST http://localhost:3000/task/create
Content-Type: application/json

{
  "title": "Task mới",
  "detail": "Mô tả task",
  "timeStart": "2024-01-01T08:00:00.000Z",
  "timeEnd": "2024-01-01T10:00:00.000Z",
  "members":  [{
    "id": "659d77d32da0e7be026ce7df",
    "userName": "HienHo2",
    "email": "12",
    "image": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
  }],
  "status": "Pending",
  "createBy": "creatorId",
  "familyId": "familyId"
}

###

# Tạo task mới
POST http://localhost:3000/task/create
Content-Type: application/json

{
  "title": "Task mới",
  "detail": "Mô tả task",
  "timeStart": "2024-01-01T08:00:00.000Z",
  "timeEnd": "2024-01-01T10:00:00.000Z",
  "members": ["memberId1", "memberId2"],
  "status": "Pending",
  "createBy":  {
    "id": "659d70dfd9b0257cdeeb66e5",
    "userName": "HienHo",
    "email": "1",
    "image": "https://cafebiz.cafebizcdn.vn/162123310254002176/2022/3/21/photo-1-1647830052032281626260.jpg"
  }
,
  "familyId": "familyId"
}

###

# Lấy danh sách task trong gia đình
GET http://localhost:3000/task/familyTasks/familyId

###

# Xoá task
DELETE http://localhost:3000/task/taskId/delete

###

# Sửa task
PATCH http://localhost:3000/task/taskId/update
Content-Type: application/json

{
  "title": "Task sửa",
  "detail": "Mô tả task sau sửa",
  "timeStart": "2024-01-01T09:00:00.000Z",
  "timeEnd": "2024-01-01T11:00:00.000Z",
  "members": ["memberId3", "memberId4"],
  "status": "Completed",
  "createBy": "creatorId2"
}

###
# Lấy danh sách tất cả gia đình
GET http://localhost:3000/family/get/getAll
